name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: list files
      run: |
        cargo install --path energiatili-import
        cargo install --path influxdb-export
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: build docker
      run: docker build -t energiatili .
    - name: run docker
      run: docker run --rm energiatili
    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: jupe/energiatili/energiatili
        tag_with_ref: true
