name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: |
        cargo test --verbose
        ls -lr
    - name: Archive build
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: |
          .cargo/**
